### ISSUE TITLE
你们要建立一个电报/qq群组吗？

### ISSUE THREAD

**Issue by zxc3123857948** [lz1998/rs-qq#8]
Linux下有一个electron-qq，这个rust-qq看起来也不错！你们有意建立一个电报群组来组织用户吗？

**Comment by lz1998** [comment]
> Linux下有一个electron-qq，这个rust-qq看起来也不错！你们有意建立一个电报群组来组织用户吗？

QQ群：982166018

**Comment by zxc3123857948** [comment]
ok，谢谢！
